"""empty message

Revision ID: 22e3d05acdd4
Revises: 3d7d5ca299fa
Create Date: 2015-02-06 10:17:29.664468

"""

# revision identifiers, used by Alembic.
revision = '22e3d05acdd4'
down_revision = '3d7d5ca299fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('message_text', sa.String(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['Member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Message')
    ### end Alembic commands ###
