"""empty message

Revision ID: 27b18e9a78f0
Revises: None
Create Date: 2015-01-23 20:14:40.296311

"""

# revision identifiers, used by Alembic.
revision = '27b18e9a78f0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('exercise_type', sa.Enum('running', 'cycling', 'swimming', name='exercise_type'), nullable=True),
    sa.Column('exercise_level', sa.Integer(), nullable=False),
    sa.Column('exercise_duration', sa.Float(), nullable=False),
    sa.Column('calories_burned', sa.Float(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['Member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Exercise')
    ### end Alembic commands ###
