"""empty message

Revision ID: 37b8cd711fec
Revises: 3d0e628f8d7b
Create Date: 2015-02-01 17:05:51.314859

"""

# revision identifiers, used by Alembic.
revision = '37b8cd711fec'
down_revision = '3d0e628f8d7b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RunningLookUp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calories_burned', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SwimmingLookUp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calories_burned', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CyclingLookUp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calories_burned', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CyclingLookUp')
    op.drop_table('SwimmingLookUp')
    op.drop_table('RunningLookUp')
    ### end Alembic commands ###
