"""empty message

Revision ID: 3d0e628f8d7b
Revises: 27b18e9a78f0
Create Date: 2015-02-01 16:54:46.284817

"""

# revision identifiers, used by Alembic.
revision = '3d0e628f8d7b'
down_revision = '27b18e9a78f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
