"""empty message

Revision ID: 3d7d5ca299fa
Revises: 24701eda5ed1
Create Date: 2015-02-03 17:14:37.105396

"""

# revision identifiers, used by Alembic.
revision = '3d7d5ca299fa'
down_revision = '24701eda5ed1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Weight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['Member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Weight', 'date')
    ### end Alembic commands ###
