"""empty message

Revision ID: 43fa86f26e14
Revises: 37b8cd711fec
Create Date: 2015-02-01 17:07:36.150504

"""

# revision identifiers, used by Alembic.
revision = '43fa86f26e14'
down_revision = '37b8cd711fec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
