"""empty message

Revision ID: 59917a989b52
Revises: 22e3d05acdd4
Create Date: 2015-02-06 10:18:35.370322

"""

# revision identifiers, used by Alembic.
revision = '59917a989b52'
down_revision = '22e3d05acdd4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
